### PR TITLE
 added scripts/nexcom.service for backend 

### PR DESCRIPTION
**Pull request by sychangww1121**

### CODE REVIEW

**Comment by tz70s** [comment]
The commit is conflict, 
use `git reset --hard HEAD~~` to keep in only one commit.

**Comment by sychangww1121** [comment]
OK, I will delete the documentation link for now.
And should the folder placement be relative user name in home ?

**Comment by tz70s** [comment]
Mmm, all right, put in root is fined. But we should add additional script to pack the modified version into it.

Just remove the link and squash your commit! Thanks!

**Comment by tz70s** [comment]
The conflict is caused by the outdated commits that I reverted. The easiest way is to backup your modification to the latest commit before `8c60298`, and add a new commit for this modification. 
[Checkout this for reset commits](https://backlogtool.com/git-tutorial/tw/stepup/stepup7_3.html)

**Pull request merged**
